### ISSUE TITLE
Strict mode: eccezione

### ISSUE THREAD

**Issue by dariomapelli** [dennybiasiolli/node-cfpiva#3]
Ciao,
viene lanciata un'altra eccezione per ulteriori variabili non dichiarate:
dopo la riga 43 scriverei
`var validi, i, s, c;`
in modo da dichiarare tutte le variabili utilizzate nel metodo.
e rimetterei la riga `validi = '0123456789'` come prima.

Ti chiederei inoltre di aggiornare il pacchetto npm nuovamente.

Ti ringrazio

**Comment by dennybiasiolli** [comment]
Tutto aggiornato, grazie ancora!
